### ISSUE TITLE
[BUG] Crash on trying to create a waypoint in 1.18

### ISSUE THREAD

**Issue by Craluminum2413** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.CampaignCartographer#35]
**Describe the Bug:**
Crash on trying to create a waypoint using `.wp` command in `1.18.0-pre.1`

**To Reproduce:**
1. Type `.wp copper` in the chat
2. It crashes

**Additional Context**
```
Running on 64 bit Windows with 16 GB RAM 
Game Version: v1.18.0-pre.1 (Unstable)
2023-02-24 15:55:08: Critical error occurred
Loaded Mods: game@1.18.0-pre.1, creative@1.18.0-pre.1, survival@1.18.0-pre.1, accessibilitytweaks@3.2.0, campaigncartographer@3.1.2, knapster@2.2.1
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at ApacheTech.VintageMods.CampaignCartographer.Services.WaypointTemplates.Extensions.WaypointTemplateExtensions.AddToMap(CoverageWaypointTemplate waypoint, BlockPos position, Boolean force)
   at Vintagestory.Common.ChatCommandApi.<>c__DisplayClass25_0.<RegisterCommand>b__0(TextCommandCallingArgs args) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 269
   at Vintagestory.Common.ChatCommandImpl.callHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 282
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientCommand(String message, Int32 groupid) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 783
   at Vintagestory.Client.NoObf.HudDialogChat.OnNewClientToServerChatLine(Int32 groupId, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 735
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerNewClientChatLine(Int32 groupid, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 337
   at Vintagestory.Client.NoObf.HudDialogChat.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 550
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 361
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2175
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(Object sender, KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 250
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.NativeWindowBase.OnKeyDown(Key key, Boolean repeat) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\NativeWindowBase.cs:line 130
   at OpenTK.Platform.Windows.WinGLNative.HandleKeyboard(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 646
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 828
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1551
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 369
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by ApacheTech** [comment]
I won't be even starting to update mods to 1.18 for a few months yet. At least until the RC release, but I usually wait until Stable, or even after the Day Zero patch.
