### ISSUE TITLE
Crash on waypoint create

### ISSUE THREAD

**Issue by kanelillym** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.CampaignCartographer#37]
**Describe the Bug:**
I am using vintage story 1.18.10, campaign cartographer 3.1.2, and debian 12. Using the chat command ".wp copper" causes the game to crash and give the following log.
After rebooting the game, I can reopen the world and am prompted to update block mapping. This process runs apparently without problem, but the game crashes instantly after several seconds.

**To Reproduce:**
- disable all mods except CC
- generate a new world
- enter ".wp copper" in the chat

**Expected Behaviour:**
No crashes, waypoint is created.

**Additional Context**
## WP add crashlog
Running on 64 bit Linux with 15852 MB RAM
Game Version: v1.18.10 (Stable)
9/17/2023 3:53:45PM: Critical error occurred in the following mod: campaigncartographer@3.1.2
Loaded Mods: game@1.18.10, creative@1.18.10, survival@1.18.10, campaigncartographer@3.1.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at ApacheTech.VintageMods.CampaignCartographer.Services.WaypointTemplates.Extensions.WaypointTemplateExtensions.AddToMap(CoverageWaypointTemplate waypoint, BlockPos position, Boolean force)
   at ApacheTech.VintageMods.CampaignCartographer.Features.PredefinedWaypoints.Commands.PredefinedWaypointsChatCommand.CallHandler(IPlayer player, Int32 groupId, CmdArgs args)
   at Vintagestory.Common.ChatCommandApi.<>c__DisplayClass26_0.<RegisterCommand>b__0(TextCommandCallingArgs args) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 291
   at Vintagestory.Common.ChatCommandImpl.callHandler(TextCommandCallingArgs callargs, Action`1 onCommandComplete, Dictionary`2 asyncParseResults) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 285
   at Vintagestory.Common.ChatCommandImpl.Execute(TextCommandCallingArgs callargs, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandImpl.cs:line 221
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, TextCommandCallingArgs args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 78
   at Vintagestory.Common.ChatCommandApi.Execute(String commandName, IClientPlayer player, Int32 groupId, String args, Action`1 onCommandComplete) in VintagestoryLib\Common\API\Command\ChatCommandApi.cs:line 165
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientCommand(String message, Int32 groupid) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 793
   at Vintagestory.Client.NoObf.HudDialogChat.HandleClientMessage(Int32 groupid, String message) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 806
   at Vintagestory.Client.NoObf.HudDialogChat.OnNewClientToServerChatLine(Int32 groupId, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 746
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerNewClientChatLine(Int32 groupid, String message, EnumChatType chattype, String data) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 335
   at Vintagestory.Client.NoObf.HudDialogChat.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\Huds\HudDialogChat.cs:line 558
   at Vintagestory.Client.NoObf.GuiManager.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 360
   at Vintagestory.Client.NoObf.ClientMain.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\ClientMain.cs:line 1725
   at Vintagestory.Client.GuiScreenRunningGame.OnKeyDown(KeyEvent args) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 310
   at Vintagestory.Client.NoObf.ClientPlatformWindows.game_KeyDown(KeyboardKeyEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 231
   at OpenTK.Windowing.Desktop.NativeWindow.KeyCallback(Window* window, Keys key, Int32 scancode, InputAction action, KeyModifiers mods)
--- End of stack trace from previous location ---
   at OpenTK.Windowing.Desktop.NativeWindow.RethrowCallbackExceptionsIfNeeded()
   at OpenTK.Windowing.Desktop.NativeWindow.ProcessWindowEvents(Boolean waitForEvents)
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

## Block mapping crashlog
Running on 64 bit Linux with 15852 MB RAM
Game Version: v1.18.10 (Stable)
9/17/2023 3:57:06PM: Critical error occurred in the following mod: campaigncartographer@3.1.2
Loaded Mods: game@1.18.10, creative@1.18.10, survival@1.18.10, campaigncartographer@3.1.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApacheTech.Common.Extensions.Harmony.HarmonyReflectionExtensions.GetField[T](Object instance, String fieldName)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.ChatCommandsApiExtensions.UnregisterCommand(ICoreClientAPI capi, String commandName)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.ChatCommandsApiExtensions.<>c__DisplayClass6_0.<UnregisterCommand>b__0(ICoreClientAPI c)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.SideAgnosticApiExtensions.RunOneOf(ICoreAPI api, Action`1 clientAction, Action`1 serverAction)
   at ApacheTech.VintageMods.FluentChatCommands.Extensions.ChatCommandsApiExtensions.UnregisterCommand(ICoreAPI api, String commandName)
   at ApacheTech.VintageMods.FluentChatCommands.FluentChat.UnregisterCommand(String commandName, ICoreAPI api)
   at ApacheTech.VintageMods.FluentChatCommands.FluentChat.ClearCommands(ICoreAPI api)
   at ApacheTech.VintageMods.CampaignCartographer.Program.Dispose()
   at Vintagestory.Client.NoObf.ClientEventAPI.TriggerLeftWorld() in VintagestoryLib\Client\API\ClientEventAPI.cs:line 358
   at Vintagestory.Client.NoObf.ClientMain.DestroyGameSession(Boolean gotDisconnected) in VintagestoryLib\Client\ClientMain.cs:line 2542
   at Vintagestory.Client.GuiScreenRunningGame.ExitOrRedirect(Boolean isDisconnect, String reason) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 273
   at Vintagestory.Client.GuiScreenRunningGame.ReloadWorld(String reason) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 261
   at Vintagestory.Client.ScreenManager.<setupHotkeyHandlers>b__48_1(KeyCombination viaKeyComb) in VintagestoryLib\Client\ScreenManager.cs:line 289
   at Vintagestory.Client.NoObf.GuiDialogConfirmRemapping.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogConfirmRemapping.cs:line 95
   at Vintagestory.Client.NoObf.GuiManager.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 324
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 76
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 312
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Chulmi** [comment]
Same exception happens to me when trying to use a translocator. I don't have auto waypoints enabled btw.

**Comment by ApacheTech** [comment]
This mod hasn't been updated since 1.17. The mod's ModDB page specifically states that it will not be updated for 1.18.
