### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by tvl83** [ApacheTech-VintageStory-Mods/ApacheTech.VintageMods.CampaignCartographer#38]
Just installed the mod. It is an existing world. 

This happened when trying to pick berries with that feature enabled to auto waypoint berries. 

Running on 64 bit Windows with 65484 MB RAM
Game Version: v1.18.15 (Stable)
04-Dec-23 01:02:24: Critical error occurred in the following mod: campaigncartographer@3.1.2
Loaded Mods: game@1.18.15, hudclock@3.3.0, creative@1.18.15, survival@1.18.15, campaigncartographer@3.1.2
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.Pos'.
   at ApacheTech.VintageMods.CampaignCartographer.Services.WaypointTemplates.Extensions.WaypointTemplateExtensions.AddToMap(CoverageWaypointTemplate waypoint, BlockPos position, Boolean force)
   at ApacheTech.VintageMods.CampaignCartographer.Features.AutoWaypoints.AutoWaypointPatchHandler.AddWaypointFor(Block block, String syntax)
   at ApacheTech.VintageMods.CampaignCartographer.Features.AutoWaypoints.AutoWaypointPatchHandler.HandleBerries(Block block)
   at ApacheTech.VintageMods.CampaignCartographer.Features.AutoWaypoints.AutoWaypointPatchHandler.HandleInteraction(Block block)
   at Vintagestory.API.Common.Block.OnBlockInteractStart_Patch1(Block this, IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel)
   at Vintagestory.GameContent.BlockBerryBush.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in VSSurvivalMod\Block\BlockBerryBush.cs:line 53
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 888
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 03-Dec-23 23:25:42, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1261.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1689.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER16C8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER16C6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1706.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_75fa4272-5a23-48a1-bd84-b429f4a69f0c

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9499e819-596b-4d44-94a9-6d74c84cff10
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 03-Dec-23 23:25:40, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x8b7c
Faulting application start time: 0x01da266f119710ae
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report Id: 9499e819-596b-4d44-94a9-6d74c84cff10
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 03-Dec-23 23:01:46, Site = , Source = Windows Error Reporting, Message = Fault bucket 1377594439300157858, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: coreclr.dll
P5: 7.0.1023.36312
P6: 64b06d6c
P7: c0000005
P8: 00000000001c98a6
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER2DF3.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER318E.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31BE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31BC.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER31FB.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_e79e3971d3dc9c44f0fc338fc32e6ee079105ae_ee8069fc_a98d2a1a-17f5-4c99-8af0-c01d621bb10d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 36593d98-e51b-4701-8f0d-f774d151b6ec
Report Status: 268435456
Hashed bucket: 84e15e300826aa29031e32d7ff0a11a2
Cab Guid: 0 }

**Comment by FireFrost76** [comment]
all auto wp will cause it to crash in 1.18 branch , just gotta wait
